# fly.toml app configuration file generated for airvienna-backend on 2023-08-25T05:17:43+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "airvienna-backend"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
