server:
  port: 8080
spring:
  profiles:
    active: default

  # Redis Setting
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  # H2 Setting Info (H2 Console을 사용하기 위한 설정)
  h2:
    console:
      enabled: true  # H2 Console을 사용할지 여부 (H2 Console을 사용하려면 true로 설정)
      path: /h2-console  # H2 Console의 경로 설정

  # Database Setting Info (데이터베이스 설정)
  datasource:
    driver-class-name: ${DB_DRIVER_CLASSNAME}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update  # update로 설정하면 테이블이 없으면 생성, 이미 있는 경우는 업데이트
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_ADDRESS}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token:
    expiration-time: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME}
  refresh-token:
    expiration-time: ${JWT_REFRESH_TOKEN_EXPIRATION_TIME}
